YOUTUBE_API_KEY = "AIzaSyAw4FGWu6rZK515FA_5ID1UkMKOG8heDxs"

[playlists]
data = [
    { name = "Excel Basic to advance  course", id = "PLbdsuU_MGf0cJolt7k6EKdSxa9JSUEqex" },
    { name = "python d318", id = "PLbdsuU_MGf0cshTlm6fADLaGco4jF5V9N" },
    { name = "AI_D309_310", id = "PLbdsuU_MGf0dx_pWVPrCSHFkDnKRg9BCB" },
    { name = "AI_311_312_313", id = "PLbdsuU_MGf0fy65MkKreMD9Tij-sbvffB" },
    { name = "Python", id = "PLbdsuU_MGf0fkY6otCnWod5gKfT4LduJG" },
    { name = "GitHub Tutorials", id = "PLbdsuU_MGf0ceELl0fzjBnK_udMxn_GFb" },
    { name = "Tech / AI News", id = "PLbdsuU_MGf0eO2RF3-W3MP4Rx_TwzNXEx" },
    { name = "Create Portfolio Website", id = "PLbdsuU_MGf0dpiE4oElItngxWji0nfDRn" },
    { name = "Tableau D322", id = "PLbdsuU_MGf0eq83haO7J1pOYdw07aSWJO" },
    { name = "sql D325", id = "PLbdsuU_MGf0eMldRU6jM-ILCF_aWGFgrQ" }
]
